// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app/ent/predicate"
	"app/ent/user"
	"app/ent/word"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WordUpdate is the builder for updating Word entities.
type WordUpdate struct {
	config
	hooks    []Hook
	mutation *WordMutation
}

// Where appends a list predicates to the WordUpdate builder.
func (_u *WordUpdate) Where(ps ...predicate.Word) *WordUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetWord sets the "word" field.
func (_u *WordUpdate) SetWord(v string) *WordUpdate {
	_u.mutation.SetWord(v)
	return _u
}

// SetNillableWord sets the "word" field if the given value is not nil.
func (_u *WordUpdate) SetNillableWord(v *string) *WordUpdate {
	if v != nil {
		_u.SetWord(*v)
	}
	return _u
}

// SetRuWord sets the "ruWord" field.
func (_u *WordUpdate) SetRuWord(v string) *WordUpdate {
	_u.mutation.SetRuWord(v)
	return _u
}

// SetNillableRuWord sets the "ruWord" field if the given value is not nil.
func (_u *WordUpdate) SetNillableRuWord(v *string) *WordUpdate {
	if v != nil {
		_u.SetRuWord(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *WordUpdate) SetLevel(v string) *WordUpdate {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *WordUpdate) SetNillableLevel(v *string) *WordUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (_u *WordUpdate) AddUserIDs(ids ...int) *WordUpdate {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUser adds the "user" edges to the User entity.
func (_u *WordUpdate) AddUser(v ...*User) *WordUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the WordMutation object of the builder.
func (_u *WordUpdate) Mutation() *WordMutation {
	return _u.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (_u *WordUpdate) ClearUser() *WordUpdate {
	_u.mutation.ClearUser()
	return _u
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (_u *WordUpdate) RemoveUserIDs(ids ...int) *WordUpdate {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUser removes "user" edges to User entities.
func (_u *WordUpdate) RemoveUser(v ...*User) *WordUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *WordUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WordUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *WordUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WordUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WordUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(word.Table, word.Columns, sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Word(); ok {
		_spec.SetField(word.FieldWord, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuWord(); ok {
		_spec.SetField(word.FieldRuWord, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(word.FieldLevel, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   word.UserTable,
			Columns: word.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserIDs(); len(nodes) > 0 && !_u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   word.UserTable,
			Columns: word.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   word.UserTable,
			Columns: word.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{word.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// WordUpdateOne is the builder for updating a single Word entity.
type WordUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *WordMutation
}

// SetWord sets the "word" field.
func (_u *WordUpdateOne) SetWord(v string) *WordUpdateOne {
	_u.mutation.SetWord(v)
	return _u
}

// SetNillableWord sets the "word" field if the given value is not nil.
func (_u *WordUpdateOne) SetNillableWord(v *string) *WordUpdateOne {
	if v != nil {
		_u.SetWord(*v)
	}
	return _u
}

// SetRuWord sets the "ruWord" field.
func (_u *WordUpdateOne) SetRuWord(v string) *WordUpdateOne {
	_u.mutation.SetRuWord(v)
	return _u
}

// SetNillableRuWord sets the "ruWord" field if the given value is not nil.
func (_u *WordUpdateOne) SetNillableRuWord(v *string) *WordUpdateOne {
	if v != nil {
		_u.SetRuWord(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *WordUpdateOne) SetLevel(v string) *WordUpdateOne {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *WordUpdateOne) SetNillableLevel(v *string) *WordUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (_u *WordUpdateOne) AddUserIDs(ids ...int) *WordUpdateOne {
	_u.mutation.AddUserIDs(ids...)
	return _u
}

// AddUser adds the "user" edges to the User entity.
func (_u *WordUpdateOne) AddUser(v ...*User) *WordUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUserIDs(ids...)
}

// Mutation returns the WordMutation object of the builder.
func (_u *WordUpdateOne) Mutation() *WordMutation {
	return _u.mutation
}

// ClearUser clears all "user" edges to the User entity.
func (_u *WordUpdateOne) ClearUser() *WordUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// RemoveUserIDs removes the "user" edge to User entities by IDs.
func (_u *WordUpdateOne) RemoveUserIDs(ids ...int) *WordUpdateOne {
	_u.mutation.RemoveUserIDs(ids...)
	return _u
}

// RemoveUser removes "user" edges to User entities.
func (_u *WordUpdateOne) RemoveUser(v ...*User) *WordUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUserIDs(ids...)
}

// Where appends a list predicates to the WordUpdate builder.
func (_u *WordUpdateOne) Where(ps ...predicate.Word) *WordUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *WordUpdateOne) Select(field string, fields ...string) *WordUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Word entity.
func (_u *WordUpdateOne) Save(ctx context.Context) (*Word, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *WordUpdateOne) SaveX(ctx context.Context) *Word {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *WordUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *WordUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *WordUpdateOne) sqlSave(ctx context.Context) (_node *Word, err error) {
	_spec := sqlgraph.NewUpdateSpec(word.Table, word.Columns, sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Word.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, word.FieldID)
		for _, f := range fields {
			if !word.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != word.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Word(); ok {
		_spec.SetField(word.FieldWord, field.TypeString, value)
	}
	if value, ok := _u.mutation.RuWord(); ok {
		_spec.SetField(word.FieldRuWord, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(word.FieldLevel, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   word.UserTable,
			Columns: word.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUserIDs(); len(nodes) > 0 && !_u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   word.UserTable,
			Columns: word.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   word.UserTable,
			Columns: word.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Word{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{word.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
