// Code generated by ent, DO NOT EDIT.

package ent

import (
	"app/ent/user"
	"app/ent/word"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// WordCreate is the builder for creating a Word entity.
type WordCreate struct {
	config
	mutation *WordMutation
	hooks    []Hook
}

// SetWord sets the "word" field.
func (_c *WordCreate) SetWord(v string) *WordCreate {
	_c.mutation.SetWord(v)
	return _c
}

// SetRuWord sets the "ruWord" field.
func (_c *WordCreate) SetRuWord(v string) *WordCreate {
	_c.mutation.SetRuWord(v)
	return _c
}

// SetLevel sets the "level" field.
func (_c *WordCreate) SetLevel(v string) *WordCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetCreatedAt sets the "createdAt" field.
func (_c *WordCreate) SetCreatedAt(v time.Time) *WordCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_c *WordCreate) SetNillableCreatedAt(v *time.Time) *WordCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// AddUserIDs adds the "user" edge to the User entity by IDs.
func (_c *WordCreate) AddUserIDs(ids ...int) *WordCreate {
	_c.mutation.AddUserIDs(ids...)
	return _c
}

// AddUser adds the "user" edges to the User entity.
func (_c *WordCreate) AddUser(v ...*User) *WordCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUserIDs(ids...)
}

// Mutation returns the WordMutation object of the builder.
func (_c *WordCreate) Mutation() *WordMutation {
	return _c.mutation
}

// Save creates the Word in the database.
func (_c *WordCreate) Save(ctx context.Context) (*Word, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *WordCreate) SaveX(ctx context.Context) *Word {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WordCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WordCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *WordCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := word.DefaultCreatedAt
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *WordCreate) check() error {
	if _, ok := _c.mutation.Word(); !ok {
		return &ValidationError{Name: "word", err: errors.New(`ent: missing required field "Word.word"`)}
	}
	if _, ok := _c.mutation.RuWord(); !ok {
		return &ValidationError{Name: "ruWord", err: errors.New(`ent: missing required field "Word.ruWord"`)}
	}
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "Word.level"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "createdAt", err: errors.New(`ent: missing required field "Word.createdAt"`)}
	}
	return nil
}

func (_c *WordCreate) sqlSave(ctx context.Context) (*Word, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *WordCreate) createSpec() (*Word, *sqlgraph.CreateSpec) {
	var (
		_node = &Word{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(word.Table, sqlgraph.NewFieldSpec(word.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Word(); ok {
		_spec.SetField(word.FieldWord, field.TypeString, value)
		_node.Word = value
	}
	if value, ok := _c.mutation.RuWord(); ok {
		_spec.SetField(word.FieldRuWord, field.TypeString, value)
		_node.RuWord = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(word.FieldLevel, field.TypeString, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(word.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2M,
			Inverse: true,
			Table:   word.UserTable,
			Columns: word.UserPrimaryKey,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// WordCreateBulk is the builder for creating many Word entities in bulk.
type WordCreateBulk struct {
	config
	err      error
	builders []*WordCreate
}

// Save creates the Word entities in the database.
func (_c *WordCreateBulk) Save(ctx context.Context) ([]*Word, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Word, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*WordMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *WordCreateBulk) SaveX(ctx context.Context) []*Word {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *WordCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *WordCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
