// Code generated by ent, DO NOT EDIT.

package word

import (
	"app/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Word {
	return predicate.Word(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Word {
	return predicate.Word(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Word {
	return predicate.Word(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Word {
	return predicate.Word(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Word {
	return predicate.Word(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Word {
	return predicate.Word(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Word {
	return predicate.Word(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Word {
	return predicate.Word(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Word {
	return predicate.Word(sql.FieldLTE(FieldID, id))
}

// Word applies equality check predicate on the "word" field. It's identical to WordEQ.
func Word(v string) predicate.Word {
	return predicate.Word(sql.FieldEQ(FieldWord, v))
}

// RuWord applies equality check predicate on the "ruWord" field. It's identical to RuWordEQ.
func RuWord(v string) predicate.Word {
	return predicate.Word(sql.FieldEQ(FieldRuWord, v))
}

// Level applies equality check predicate on the "level" field. It's identical to LevelEQ.
func Level(v string) predicate.Word {
	return predicate.Word(sql.FieldEQ(FieldLevel, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Word {
	return predicate.Word(sql.FieldEQ(FieldCreatedAt, v))
}

// WordEQ applies the EQ predicate on the "word" field.
func WordEQ(v string) predicate.Word {
	return predicate.Word(sql.FieldEQ(FieldWord, v))
}

// WordNEQ applies the NEQ predicate on the "word" field.
func WordNEQ(v string) predicate.Word {
	return predicate.Word(sql.FieldNEQ(FieldWord, v))
}

// WordIn applies the In predicate on the "word" field.
func WordIn(vs ...string) predicate.Word {
	return predicate.Word(sql.FieldIn(FieldWord, vs...))
}

// WordNotIn applies the NotIn predicate on the "word" field.
func WordNotIn(vs ...string) predicate.Word {
	return predicate.Word(sql.FieldNotIn(FieldWord, vs...))
}

// WordGT applies the GT predicate on the "word" field.
func WordGT(v string) predicate.Word {
	return predicate.Word(sql.FieldGT(FieldWord, v))
}

// WordGTE applies the GTE predicate on the "word" field.
func WordGTE(v string) predicate.Word {
	return predicate.Word(sql.FieldGTE(FieldWord, v))
}

// WordLT applies the LT predicate on the "word" field.
func WordLT(v string) predicate.Word {
	return predicate.Word(sql.FieldLT(FieldWord, v))
}

// WordLTE applies the LTE predicate on the "word" field.
func WordLTE(v string) predicate.Word {
	return predicate.Word(sql.FieldLTE(FieldWord, v))
}

// WordContains applies the Contains predicate on the "word" field.
func WordContains(v string) predicate.Word {
	return predicate.Word(sql.FieldContains(FieldWord, v))
}

// WordHasPrefix applies the HasPrefix predicate on the "word" field.
func WordHasPrefix(v string) predicate.Word {
	return predicate.Word(sql.FieldHasPrefix(FieldWord, v))
}

// WordHasSuffix applies the HasSuffix predicate on the "word" field.
func WordHasSuffix(v string) predicate.Word {
	return predicate.Word(sql.FieldHasSuffix(FieldWord, v))
}

// WordEqualFold applies the EqualFold predicate on the "word" field.
func WordEqualFold(v string) predicate.Word {
	return predicate.Word(sql.FieldEqualFold(FieldWord, v))
}

// WordContainsFold applies the ContainsFold predicate on the "word" field.
func WordContainsFold(v string) predicate.Word {
	return predicate.Word(sql.FieldContainsFold(FieldWord, v))
}

// RuWordEQ applies the EQ predicate on the "ruWord" field.
func RuWordEQ(v string) predicate.Word {
	return predicate.Word(sql.FieldEQ(FieldRuWord, v))
}

// RuWordNEQ applies the NEQ predicate on the "ruWord" field.
func RuWordNEQ(v string) predicate.Word {
	return predicate.Word(sql.FieldNEQ(FieldRuWord, v))
}

// RuWordIn applies the In predicate on the "ruWord" field.
func RuWordIn(vs ...string) predicate.Word {
	return predicate.Word(sql.FieldIn(FieldRuWord, vs...))
}

// RuWordNotIn applies the NotIn predicate on the "ruWord" field.
func RuWordNotIn(vs ...string) predicate.Word {
	return predicate.Word(sql.FieldNotIn(FieldRuWord, vs...))
}

// RuWordGT applies the GT predicate on the "ruWord" field.
func RuWordGT(v string) predicate.Word {
	return predicate.Word(sql.FieldGT(FieldRuWord, v))
}

// RuWordGTE applies the GTE predicate on the "ruWord" field.
func RuWordGTE(v string) predicate.Word {
	return predicate.Word(sql.FieldGTE(FieldRuWord, v))
}

// RuWordLT applies the LT predicate on the "ruWord" field.
func RuWordLT(v string) predicate.Word {
	return predicate.Word(sql.FieldLT(FieldRuWord, v))
}

// RuWordLTE applies the LTE predicate on the "ruWord" field.
func RuWordLTE(v string) predicate.Word {
	return predicate.Word(sql.FieldLTE(FieldRuWord, v))
}

// RuWordContains applies the Contains predicate on the "ruWord" field.
func RuWordContains(v string) predicate.Word {
	return predicate.Word(sql.FieldContains(FieldRuWord, v))
}

// RuWordHasPrefix applies the HasPrefix predicate on the "ruWord" field.
func RuWordHasPrefix(v string) predicate.Word {
	return predicate.Word(sql.FieldHasPrefix(FieldRuWord, v))
}

// RuWordHasSuffix applies the HasSuffix predicate on the "ruWord" field.
func RuWordHasSuffix(v string) predicate.Word {
	return predicate.Word(sql.FieldHasSuffix(FieldRuWord, v))
}

// RuWordEqualFold applies the EqualFold predicate on the "ruWord" field.
func RuWordEqualFold(v string) predicate.Word {
	return predicate.Word(sql.FieldEqualFold(FieldRuWord, v))
}

// RuWordContainsFold applies the ContainsFold predicate on the "ruWord" field.
func RuWordContainsFold(v string) predicate.Word {
	return predicate.Word(sql.FieldContainsFold(FieldRuWord, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v string) predicate.Word {
	return predicate.Word(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v string) predicate.Word {
	return predicate.Word(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...string) predicate.Word {
	return predicate.Word(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...string) predicate.Word {
	return predicate.Word(sql.FieldNotIn(FieldLevel, vs...))
}

// LevelGT applies the GT predicate on the "level" field.
func LevelGT(v string) predicate.Word {
	return predicate.Word(sql.FieldGT(FieldLevel, v))
}

// LevelGTE applies the GTE predicate on the "level" field.
func LevelGTE(v string) predicate.Word {
	return predicate.Word(sql.FieldGTE(FieldLevel, v))
}

// LevelLT applies the LT predicate on the "level" field.
func LevelLT(v string) predicate.Word {
	return predicate.Word(sql.FieldLT(FieldLevel, v))
}

// LevelLTE applies the LTE predicate on the "level" field.
func LevelLTE(v string) predicate.Word {
	return predicate.Word(sql.FieldLTE(FieldLevel, v))
}

// LevelContains applies the Contains predicate on the "level" field.
func LevelContains(v string) predicate.Word {
	return predicate.Word(sql.FieldContains(FieldLevel, v))
}

// LevelHasPrefix applies the HasPrefix predicate on the "level" field.
func LevelHasPrefix(v string) predicate.Word {
	return predicate.Word(sql.FieldHasPrefix(FieldLevel, v))
}

// LevelHasSuffix applies the HasSuffix predicate on the "level" field.
func LevelHasSuffix(v string) predicate.Word {
	return predicate.Word(sql.FieldHasSuffix(FieldLevel, v))
}

// LevelEqualFold applies the EqualFold predicate on the "level" field.
func LevelEqualFold(v string) predicate.Word {
	return predicate.Word(sql.FieldEqualFold(FieldLevel, v))
}

// LevelContainsFold applies the ContainsFold predicate on the "level" field.
func LevelContainsFold(v string) predicate.Word {
	return predicate.Word(sql.FieldContainsFold(FieldLevel, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.Word {
	return predicate.Word(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.Word {
	return predicate.Word(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.Word {
	return predicate.Word(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Word {
	return predicate.Word(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.Word {
	return predicate.Word(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.Word {
	return predicate.Word(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.Word {
	return predicate.Word(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.Word {
	return predicate.Word(sql.FieldLTE(FieldCreatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2M, true, UserTable, UserPrimaryKey...),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Word {
	return predicate.Word(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Word) predicate.Word {
	return predicate.Word(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Word) predicate.Word {
	return predicate.Word(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Word) predicate.Word {
	return predicate.Word(sql.NotPredicates(p))
}
